FROM metocean/ops-libs:3.6-master

ADD . $SOURCE/moana-qc

ARG GIT_TOKEN

RUN pip install -r $SOURCE/moana-qc/requirements/default.txt &&\
    pip install -I -r $SOURCE/moana-qc/requirements/opslibs.txt &&\
    pip install -r $SOURCE/moana-qc/requirements/tests.txt &&\
    pip install $SOURCE/moana-qc

CMD ["/bin/bash"]
