FROM metocean/ops-libs:3.8-master

ADD . $SOURCE/moana-qc

ARG GIT_TOKEN

RUN pip install -r $SOURCE/moana-qc/requirements/default.txt &&\
    pip install -I -r $SOURCE/moana-qc/requirements/opslibs.txt &&\
    pip install -r $SOURCE/moana-qc/requirements/tests.txt &&\
    pip install $SOURCE/moana-qc &&\\
    pip uninstall cloudpickle &&\\
    pip uninstall ops-mds &&\\
    pip uninstall snowflake-sqlalchemy &&\\
    pip install pytz==2023.3 &&\\
    pip install SQLAlchemy==1.1.18


CMD ["/bin/bash"]
